title: Janko's Blog
description: Sharing the wonders of Ruby
url: https://janko.io
logo: /images/logo.png

author:
  name: Janko Marohnić
  image: /images/me.jpg
  github: janko
  twitter: jankomarohnic
  email: janko@hey.com
  facebook: janko.marohnic

# for jekyll-seo-tag
twitter:
  username: jankomarohnic
  card: summary
facebook:
  publisher: https://www.facebook.com/janko.marohnic/
github:
  url: https://github.com/janko/janko.io

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: default
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      permalink: /:title/
      comments: utterances
  - scope:
      path: ""
      type: drafts
    values:
      layout: post

kramdown:
  footnote_backlink: ↩︎

exclude:
  - Gemfile
  - Gemfile.lock
  - package.json
  - yarn.lock
  - readme.md
  - .gitignore
  - node_modules
  - css/application.css
  - css/highlight.css
  - tailwind.config.js
  - postcss.config.js
